#!/bin/bash
echo "=========================================="
echo "  GPU Verification for OKE"
echo "=========================================="
echo ""
echo "CUDA Version:"
nvcc --version 2>/dev/null || echo "nvcc not in PATH"
echo ""
echo "NVIDIA Driver:"
nvidia-smi --query-gpu=driver_version --format=csv,noheader 2>/dev/null || echo "nvidia-smi not available (expected during build)"
echo ""
echo "GPU Info:"
nvidia-smi --query-gpu=name,memory.total,compute_cap --format=csv 2>/dev/null || echo "GPU info not available"
echo ""
echo "NCCL Settings:"
env | grep -E "^NCCL_" | sort || echo "No NCCL env vars set"
echo ""
echo "nsys Version:"
nsys --version 2>/dev/null | head -1 || echo "nsys not found"
echo ""
echo "=========================================="
